<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Data Gudang</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            background-color: #f4f7fa;
            color: #333;
        }

        h2 {
            text-align: center;
            color: #2c3e50;
            font-size: 24px;
            margin-bottom: 20px;
        }

        .header {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #2980b9;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th {
            background-color: #2980b9;
            color: white;
            text-align: center;
            padding: 12px;
            font-size: 14px;
        }

        td {
            text-align: left;
            padding: 10px;
            font-size: 13px;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tbody tr:hover {
            background-color: #e2e2e2;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #7f8c8d;
        }

        .footer p {
            margin: 5px 0;
        }

        .table-container {
            margin: 0 auto;
            width: 90%;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <h2>Product Data Gudang PT. Export Fakhri</h2>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Product Name</th>
                    <th>Unit</th>
                    <th>Type</th>
                    <th>Information</th>
                    <th>Qty</th>
                    <th>Producer</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $key => $product)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $product->product_name }}</td>
                        <td>{{ $product->unit }}</td>
                        <td>{{ $product->type }}</td>
                        <td>{{ $product->information }}</td>
                        <td>{{ $product->qty }}</td>
                        <td>{{ $product->producer }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="footer">
        <p>Generated by PT. Export Fakhri - Warehouse Management System</p>
        <p>© 2024 PT. Export Fakhri | All Rights Reserved</p>
    </div>
</body>
</html>
